data:
  input_path: data/inputLearnText.txt

training:
  sequence_length: 64
  epochs: 50
  batch_size: 64
  shuffle: true

validation:
  input_path: ${data.input_path}

model:
  embed_size: 384
  num_heads: 6
  num_layers: 6
  dropout: 0.1

optimizer:
  lr: 0.001
  weight_decay: 0.0

artifacts:
  checkpoints_dir: artifacts/checkpoints
  tokenizers_dir: artifacts/tokenizers
  tokenizer_filename: tokenizer.json

wandb:
  enabled: true
  project: llm-scratch
  entity: sunday-research
  name: null
  mode: online

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
